package com.demo.models;
// Generated Jan 3, 2022, 9:43:46 AM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "account", catalog = "auctionhunter")
public class Account implements java.io.Serializable {

	private Integer id;
	private String username;
	private String password;
	private String fullName;
	private String sex;
	private String avatar;
	private String email;
	private String phone;
	private String address;
	private Date dob;
	private String role;
	private int report;
	private boolean isDelete;
	private Set<Cart> carts = new HashSet<Cart>(0);
	private Set<HistoryAuction> historyAuctions = new HashSet<HistoryAuction>(0);
	private Set<Invoice> invoices = new HashSet<Invoice>(0);
	private Set<Product> products = new HashSet<Product>(0);

	public Account() {
	}

	public Account(String username, String password, String fullName, String sex, String avatar, String email,
			String phone, String address, Date dob, String role, int report, boolean isDelete) {
		this.username = username;
		this.password = password;
		this.fullName = fullName;
		this.sex = sex;
		this.avatar = avatar;
		this.email = email;
		this.phone = phone;
		this.address = address;
		this.dob = dob;
		this.role = role;
		this.report = report;
		this.isDelete = isDelete;
	}

	public Account(String username, String password, String fullName, String sex, String avatar, String email,
			String phone, String address, Date dob, String role, int report, boolean isDelete, Set<Cart> carts,
			Set<HistoryAuction> historyAuctions, Set<Invoice> invoices, Set<Product> products) {
		this.username = username;
		this.password = password;
		this.fullName = fullName;
		this.sex = sex;
		this.avatar = avatar;
		this.email = email;
		this.phone = phone;
		this.address = address;
		this.dob = dob;
		this.role = role;
		this.report = report;
		this.isDelete = isDelete;
		this.carts = carts;
		this.historyAuctions = historyAuctions;
		this.invoices = invoices;
		this.products = products;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "username", nullable = false, length = 250)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 250)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "full_name", nullable = false, length = 250)
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@Column(name = "sex", nullable = false, length = 20)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Column(name = "avatar", nullable = false, length = 250)
	public String getAvatar() {
		return this.avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	@Column(name = "email", nullable = false, length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone", nullable = false, length = 50)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "address", nullable = false, length = 250)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dob", nullable = false, length = 10)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Column(name = "role", nullable = false, length = 50)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Column(name = "report", nullable = false)
	public int getReport() {
		return this.report;
	}

	public void setReport(int report) {
		this.report = report;
	}

	@Column(name = "isDelete", nullable = false)
	public boolean isIsDelete() {
		return this.isDelete;
	}

	public void setIsDelete(boolean isDelete) {
		this.isDelete = isDelete;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Cart> getCarts() {
		return this.carts;
	}

	public void setCarts(Set<Cart> carts) {
		this.carts = carts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<HistoryAuction> getHistoryAuctions() {
		return this.historyAuctions;
	}

	public void setHistoryAuctions(Set<HistoryAuction> historyAuctions) {
		this.historyAuctions = historyAuctions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Invoice> getInvoices() {
		return this.invoices;
	}

	public void setInvoices(Set<Invoice> invoices) {
		this.invoices = invoices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
