package com.demo.models;
// Generated Jan 18, 2022, 8:06:39 AM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BrandProductId generated by hbm2java
 */
@Embeddable
public class BrandProductId implements java.io.Serializable {

	private int productId;
	private int brandId;

	public BrandProductId() {
	}

	public BrandProductId(int productId, int brandId) {
		this.productId = productId;
		this.brandId = brandId;
	}

	@Column(name = "product_id", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	@Column(name = "brand_id", nullable = false)
	public int getBrandId() {
		return this.brandId;
	}

	public void setBrandId(int brandId) {
		this.brandId = brandId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BrandProductId))
			return false;
		BrandProductId castOther = (BrandProductId) other;

		return (this.getProductId() == castOther.getProductId()) && (this.getBrandId() == castOther.getBrandId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProductId();
		result = 37 * result + this.getBrandId();
		return result;
	}

}
