package com.demo.models;
// Generated Jan 18, 2022, 8:06:39 AM by Hibernate Tools 5.1.10.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BrandProduct generated by hbm2java
 */
@Entity
@Table(name = "brand_product", catalog = "auctionhunter")
public class BrandProduct implements java.io.Serializable {

	private BrandProductId id;
	private Brand brand;
	private Product product;

	public BrandProduct() {
	}

	public BrandProduct(BrandProductId id, Brand brand, Product product) {
		this.id = id;
		this.brand = brand;
		this.product = product;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "productId", column = @Column(name = "product_id", nullable = false)),
			@AttributeOverride(name = "brandId", column = @Column(name = "brand_id", nullable = false)) })
	public BrandProductId getId() {
		return this.id;
	}

	public void setId(BrandProductId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "brand_id", nullable = false, insertable = false, updatable = false)
	public Brand getBrand() {
		return this.brand;
	}

	public void setBrand(Brand brand) {
		this.brand = brand;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false, insertable = false, updatable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

}
