package com.demo.models;
// Generated Jan 18, 2022, 8:06:39 AM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CategoryProductId generated by hbm2java
 */
@Embeddable
public class CategoryProductId implements java.io.Serializable {

	private int productId;
	private int categoryId;

	public CategoryProductId() {
	}

	public CategoryProductId(int productId, int categoryId) {
		this.productId = productId;
		this.categoryId = categoryId;
	}

	@Column(name = "product_id", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	@Column(name = "category_id", nullable = false)
	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CategoryProductId))
			return false;
		CategoryProductId castOther = (CategoryProductId) other;

		return (this.getProductId() == castOther.getProductId()) && (this.getCategoryId() == castOther.getCategoryId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProductId();
		result = 37 * result + this.getCategoryId();
		return result;
	}

}
