package com.demo.models;
// Generated Jan 18, 2022, 8:06:39 AM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * HistoryAuction generated by hbm2java
 */
@Entity
@Table(name = "history_auction", catalog = "auctionhunter")
public class HistoryAuction implements java.io.Serializable {

	private Integer id;
	private Account account;
	private Product product;
	private boolean status;
	private double priceBid;
	
	@DateTimeFormat(pattern = "dd/MM/yyyy HH:mm:ss")
	private Date dateBid;

	public HistoryAuction() {
	}

	public HistoryAuction(Account account, Product product, boolean status, double priceBid, Date dateBid) {
		this.account = account;
		this.product = product;
		this.status = status;
		this.priceBid = priceBid;
		this.dateBid = dateBid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_id", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Column(name = "price_bid", nullable = false, precision = 22, scale = 0)
	public double getPriceBid() {
		return this.priceBid;
	}

	public void setPriceBid(double priceBid) {
		this.priceBid = priceBid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_bid", nullable = false, length = 19)
	public Date getDateBid() {
		return this.dateBid;
	}

	public void setDateBid(Date dateBid) {
		this.dateBid = dateBid;
	}

}
